# Generated by Django 2.2.6 on 2020-01-13 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingIngestMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, db_column='id', primary_key=True, serialize=False)),
                ('ingest_date', models.DateTimeField(db_column='ingest_date')),
                ('file_blob', models.FileField(db_column='file_content_as_blob', upload_to='')),
                ('file_name', models.CharField(db_column='file_name', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='usermaster',
            name='status',
            field=models.CharField(db_column='status', default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userroleassociation',
            name='status',
            field=models.CharField(db_column='status', default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermaster',
            name='mapping_id',
            field=models.ForeignKey(db_column='mapping_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='services.MappingIngestMaster'),
        ),
        migrations.AddField(
            model_name='userroleassociation',
            name='mapping_id',
            field=models.ForeignKey(db_column='mapping_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='services.MappingIngestMaster'),
            preserve_default=False,
        ),
    ]
