# Generated by Django 2.2.6 on 2020-01-13 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200113_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemaster',
            name='mapping_id',
            field=models.ForeignKey(db_column='mapping_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='services.MappingIngestMaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userroleassociation',
            name='user_id',
            field=models.CharField(db_column='user_id', max_length=7),
        ),
        migrations.DeleteModel(
            name='UserMaster',
        ),
    ]
